'use client';
import { useEffect,useState } from 'react';
import { categories } from '@/lib/designmash/data';
import { Shell } from './shell';
export function AddForm(){
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ok,setOk]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget;setBusy(true);setOk(false);setMessage('');try{const r=await fetch('/api/submissions',{method:'POST',body:new FormData(form)});const data=await r.json();if(!r.ok)throw new Error(data.error);setOk(true);setMessage('Submitted. Your entry will appear after it has been reviewed.');form.reset();}catch(e){setMessage(e instanceof Error?e.message:'Could not submit. Please try again.');}finally{setBusy(false);}}
  return <Shell><h1>Add Something</h1><form className="form" onSubmit={submit}><p className="note">Submissions are reviewed before they appear. Upload an image you have permission to share.</p><label htmlFor="category">Category</label><select name="category" id="category" defaultValue="logos">{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><label htmlFor="name">Name *</label><input id="name" name="name" required maxLength={100}/><label htmlFor="company">Company / Creator</label><input id="company" name="company" maxLength={100}/><label htmlFor="website">Website URL</label><input id="website" name="website_url" type="url" maxLength={2048} placeholder="https://"/><label htmlFor="image">Image / Screenshot</label><input id="image" name="image" type="file" accept="image/png,image/jpeg,image/webp"/><p className="note">PNG, JPEG, or WebP. Up to 5 MB. Images are optional for NAMES.</p><label htmlFor="source">Source URL</label><input id="source" name="source_url" type="url" maxLength={2048} placeholder="https://"/><button className="plain-button" disabled={busy}>{busy?'Submitting…':'Submit'}</button><p className={`status ${ok?'':'error'}`} role="status">{message}</p></form></Shell>;
}
export function RemovalForm(){
  const [item,setItem]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ok,setOk]=useState(false);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get('item');if(value){try{const u=new URL(value,window.location.origin);if(u.origin===window.location.origin)setItem(u.href);}catch{}}},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget;setBusy(true);setMessage('');setOk(false);try{const body=Object.fromEntries(new FormData(form));const r=await fetch('/api/removal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setOk(true);setMessage('Request received. We will review it.');form.reset();setItem('');}catch(e){setMessage(e instanceof Error?e.message:'Could not submit. Please try again.');}finally{setBusy(false);}}
  return <Shell><h1>See something here that shouldn’t be?</h1><form className="form" onSubmit={submit}><label htmlFor="item-url">Item URL *</label><input id="item-url" name="item_url" type="url" required maxLength={2048} value={item} onChange={e=>setItem(e.target.value)}/><label htmlFor="reason">Reason *</label><textarea id="reason" name="reason" required maxLength={1000}/><label htmlFor="email">Email *</label><input id="email" name="email" type="email" required maxLength={254}/><label htmlFor="information">Additional information</label><textarea id="information" name="additional_information" maxLength={4000}/><button className="plain-button" disabled={busy}>{busy?'Submitting…':'Submit Removal Request'}</button><p className={`status ${ok?'':'error'}`} role="status">{message}</p></form></Shell>;
}
