'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Entry, categoryLabel } from '@/lib/designmash/data';
import { Shell } from './shell';
import { EntryImage } from './image';
type Detail={item:Entry;rank:number;history:{opponent_id:string;name:string;slug:string;wins:number;losses:number}[];recent:{id:string;winner?:Entry;loser?:Entry;winner_id:string;created_at:string}[]};
export function Item({slug}:{slug:string}){
  const [data,setData]=useState<Detail|null>(null),[error,setError]=useState('');
  useEffect(()=>{let alive=true;fetch(`/api/item/${encodeURIComponent(slug)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[slug]);
  const e=data?.item;
  return <Shell>{e&&data?<><div className="content center"><div className="item-picture"><EntryImage entry={e}/></div><h1>{e.name}</h1><p>#{data.rank} in {categoryLabel(e.category_id)}</p><p className="creator">{e.company}</p>{e.website_url&&<p><a href={e.website_url} target="_blank" rel="noopener noreferrer">{new URL(e.website_url).hostname}</a></p>}<dl className="stats"><dt>Elo</dt><dd>{Math.round(e.elo_rating).toLocaleString()}</dd><dt>Win Rate</dt><dd>{e.total_votes?`${(e.wins/e.total_votes*100).toFixed(1)}%`:'—'}</dd><dt>Wins</dt><dd>{e.wins}</dd><dt>Losses</dt><dd>{e.losses}</dd><dt>Battles</dt><dd>{e.total_votes}</dd></dl><div className="opponents" style={{textAlign:'left'}}>{[['MOST OFTEN BEATS','wins'],['MOST OFTEN LOSES TO','losses']].map(([label,key])=>{const rows=[...data.history].filter(x=>x[key as 'wins'|'losses']>0).sort((a,b)=>b[key as 'wins'|'losses']-a[key as 'wins'|'losses']).slice(0,5);return <section key={key}><h2>{label}</h2>{rows.length?<ul>{rows.map(r=><li key={r.opponent_id}><Link href={`/item/${r.slug}`}>{r.name}</Link> ({r[key as 'wins'|'losses']})</li>)}</ul>:<p className="note">No matchups yet.</p>}</section>;})}</div><h2>RECENT MATCHUPS</h2>{data.recent.length?<div className="table-wrap"><table><thead><tr><th>OPPONENT</th><th>RESULT</th><th>DATE</th></tr></thead><tbody>{data.recent.map(v=>{const won=v.winner_id===e.id;const opponent=won?v.loser:v.winner;return <tr key={v.id}><td>{opponent?<Link href={`/item/${opponent.slug}`}>{opponent.name}</Link>:'Unavailable entry'}</td><td>{won?'Won':'Lost'}</td><td>{new Date(v.created_at).toLocaleDateString()}</td></tr>;})}</tbody></table></div>:<p className="note">No votes yet. The science has to start somewhere.</p>}<p><Link href={`/${e.category_id}`}>Back to Voting</Link></p><p className="note"><Link href={`/removal?item=${encodeURIComponent(`/item/${e.slug}`)}`}>Request removal</Link>{e.source_url&&<> · <a href={e.source_url} target="_blank" rel="noopener noreferrer">Source</a></>}</p></div></>:<div className="content center"><p role="status">{error||'Loading entry…'}</p><Link href="/">Back to Voting</Link></div>}</Shell>;
}
