'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Category, Entry, categories, seedEntries, isCategory } from '@/lib/designmash/data';
import { Shell, CategoryLinks } from './shell';
export function Rankings(){
  const [category,setCategory]=useState<Category>('logos'),[period,setPeriod]=useState('all'),[rows,setRows]=useState<Entry[]>(seedEntries.filter(e=>e.category_id==='logos')),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{const c=new URLSearchParams(window.location.search).get('category');if(c&&isCategory(c))setCategory(c);},[]);
  useEffect(()=>{let alive=true;setLoading(true);setError('');fetch(`/api/rankings?category=${category}&period=${period}`,{cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);if(alive){setRows(data.entries);if(!data.configured)setError('Rankings are waiting for the database connection. All sample entries start at 1500.');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[category,period]);
  return <Shell><h1 className="page-title">Rankings</h1><nav className="categories" aria-label="Ranking categories">{categories.map(c=><a href={`/rankings?category=${c.slug}`} key={c.slug} onClick={e=>{e.preventDefault();setCategory(c.slug);window.history.replaceState(null,'',`/rankings?category=${c.slug}`);}} className={category===c.slug?'active':''}>{c.name}</a>)}</nav><div className="filters">{[['today','TODAY'],['week','WEEK'],['month','MONTH'],['all','ALL TIME']].map(([id,label])=><button key={id} className={period===id?'active':''} aria-pressed={period===id} onClick={()=>setPeriod(id)}>{label}</button>)}</div><div className="content"><p className="note">Rating is current Elo. W–L and win % cover the selected period{period==='today'?' (UTC)':''}.</p><div className="table-wrap" aria-busy={loading}><table><thead><tr><th>RANK</th><th>NAME</th><th>RATING</th><th>W–L</th><th>WIN %</th></tr></thead><tbody>{rows.map((e,i)=><tr key={e.id}><td>{i+1}</td><td><Link href={`/item/${e.slug}`}>{e.name}</Link></td><td>{Math.round(e.elo_rating).toLocaleString()}</td><td>{e.wins}–{e.losses}</td><td>{e.total_votes?`${(e.wins/e.total_votes*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div>{!rows.length&&!loading&&<p className="empty">No entries yet.</p>}<p className="status error" role="status">{error}</p><p><Link href={`/${category}`}>Back to Voting</Link></p></div></Shell>;
}
